# Generated by Django 5.0.6 on 2024-05-17 12:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(null=True, upload_to=app.models.get_img_upload_path),
        ),
    ]
