# Generated by Django 5.0.6 on 2024-05-17 18:50

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_celebrity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.TextField(blank=True, max_length=200, unique=True, verbose_name='Photo Name')),
                ('photo', models.ImageField(upload_to=app.models.path_generator)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='NA', max_length=100, unique=True, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='photos',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.project'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Tag Description'),
        ),
    ]
