# Generated by Django 5.0.6 on 2024-05-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_photos_delete_contacts_delete_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='{Project.name}{path_generator}'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Photo Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Project Name'),
        ),
    ]
