# Generated by Django 5.0.6 on 2024-05-21 05:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_photos_photo_alter_photos_photo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to=app.models.path_slider)),
            ],
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to=app.models.path_generator),
        ),
    ]
